<?php

namespace AppBundle\Repository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository {

    public function myFindAll() {

        $query = $this->_em->createQuery('SELECT e.id, e.nom  FROM AppBundle:Event e');
        return $query->getResult();
    }

    

}
